export const CONTINENTS = [
  "Asia",
  "Europe",
  "Africa",
  "North America",
  "South America",
  "Australia",
  "Antarctica",
];

export const COUNTRIES_BY_CONTINENT = {
  Asia: [
    "China",
    "India",
    "Japan",
    "South Korea",
    "Thailand",
    "Singapore",
    "Malaysia",
    "Indonesia",
    "Philippines",
    "Vietnam",
  ],
  Europe: [
    "United Kingdom",
    "Germany",
    "France",
    "Italy",
    "Spain",
    "Netherlands",
    "Switzerland",
    "Russia",
    "Turkey",
    "Sweden",
  ],
  Africa: [
    "South Africa",
    "Egypt",
    "Morocco",
    "Kenya",
    "Nigeria",
    "Ethiopia",
    "Ghana",
    "Tanzania",
    "Uganda",
    "Zambia",
  ],
  "North America": [
    "United States",
    "Canada",
    "Mexico",
    "Cuba",
    "Jamaica",
    "Costa Rica",
    "Panama",
    "Guatemala",
    "Dominican Republic",
  ],
  "South America": [
    "Brazil",
    "Argentina",
    "Chile",
    "Colombia",
    "Peru",
    "Venezuela",
    "Ecuador",
    "Bolivia",
    "Uruguay",
    "Paraguay",
  ],
  Australia: [
    "Australia",
    "New Zealand",
    "Fiji",
    "Papua New Guinea",
    "Samoa",
    "Tonga",
    "Vanuatu",
    "Solomon Islands",
  ],
  Antarctica: ["Antarctica"],
};

export const CITIES_BY_COUNTRY = {
  "United States": [
    "New York",
    "Los Angeles",
    "Chicago",
    "Houston",
    "Phoenix",
    "Philadelphia",
    "San Antonio",
    "San Diego",
    "Dallas",
    "San Jose",
  ],
  "United Kingdom": [
    "London",
    "Manchester",
    "Birmingham",
    "Leeds",
    "Glasgow",
    "Sheffield",
    "Bradford",
    "Liverpool",
    "Edinburgh",
    "Bristol",
  ],
  Germany: [
    "Berlin",
    "Hamburg",
    "Munich",
    "Cologne",
    "Frankfurt",
    "Stuttgart",
    "Düsseldorf",
    "Dortmund",
    "Essen",
    "Leipzig",
  ],
  France: [
    "Paris",
    "Marseille",
    "Lyon",
    "Toulouse",
    "Nice",
    "Nantes",
    "Strasbourg",
    "Montpellier",
    "Bordeaux",
    "Lille",
  ],
  China: [
    "Beijing",
    "Shanghai",
    "Guangzhou",
    "Shenzhen",
    "Chengdu",
    "Hangzhou",
    "Wuhan",
    "Xi'an",
    "Suzhou",
    "Tianjin",
  ],
  Japan: [
    "Tokyo",
    "Yokohama",
    "Osaka",
    "Nagoya",
    "Sapporo",
    "Fukuoka",
    "Kobe",
    "Kawasaki",
    "Kyoto",
    "Saitama",
  ],
  India: [
    "Delhi",
    "Mumbai",
    "Bangalore",
    "Hyderabad",
    "Ahmedabad",
    "Chennai",
    "Kolkata",
    "Surat",
    "Pune",
    "Jaipur",
  ],
  Thailand: ["Bangkok", "Nonthaburi", "Nakhon Ratchasima", "Chiang Mai", "Phuket"],
  Singapore: ["Singapore"],
  Malaysia: ["Kuala Lumpur", "Klang", "Ipoh", "George Town", "Petaling Jaya"],
  Indonesia: ["Jakarta", "Surabaya", "Bekasi", "Bandung", "Medan"],
  Philippines: ["Quezon City", "Manila", "Davao City", "Caloocan", "Cebu City"],
  Vietnam: ["Ho Chi Minh City", "Hanoi", "Da Nang", "Haiphong", "Can Tho"],
  Italy: ["Rome", "Milan", "Naples", "Turin", "Palermo"],
  Spain: ["Madrid", "Barcelona", "Valencia", "Seville", "Zaragoza"],
  Netherlands: ["Amsterdam", "Rotterdam", "The Hague", "Utrecht", "Eindhoven"],
  Switzerland: ["Zürich", "Geneva", "Basel", "Lausanne", "Bern"],
  Russia: ["Moscow", "Saint Petersburg", "Novosibirsk", "Yekaterinburg", "Kazan"],
  Turkey: ["Istanbul", "Ankara", "Izmir", "Bursa", "Adana"],
  Sweden: ["Stockholm", "Gothenburg", "Malmö", "Uppsala", "Västerås"],
  "South Africa": ["Johannesburg", "Cape Town", "Durban", "Pretoria", "Port Elizabeth"],
  Egypt: ["Cairo", "Alexandria", "Giza", "Shubra El Kheima", "Port Said"],
  Morocco: ["Casablanca", "Fez", "Tangier", "Marrakesh", "Salé"],
  Kenya: ["Nairobi", "Mombasa", "Nakuru", "Kisumu", "Eldoret"],
  Nigeria: ["Lagos", "Kano", "Ibadan", "Benin City", "Port Harcourt"],
  Canada: ["Toronto", "Montreal", "Vancouver", "Ottawa", "Calgary"],
  Mexico: ["Mexico City", "Ecatepec de Morelos", "Guadalajara", "Puebla City", "Ciudad Juárez"],
  Brazil: ["São Paulo", "Rio de Janeiro", "Brasília", "Salvador", "Fortaleza"],
  Argentina: ["Buenos Aires", "Córdoba", "Rosario", "Mendoza", "La Plata"],
  Chile: ["Santiago", "Valparaíso", "Concepción", "La Serena", "Antofagasta"],
  Australia: ["Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide"],
  "New Zealand": ["Auckland", "Wellington", "Christchurch", "Hamilton", "Tauranga"],
};
